// This exports Schema.graphql
import { writeFileSync } from "node:fs";
import { printSubgraphSchema } from "@apollo/subgraph";

import { schema } from "../dist/graphql/schema.js";
const destinationPath = "./src/graphql/generated/schema.graphql";

// Patches pending fixes from: https://github.com/apollographql/federation/pull/1831
const schemaText = printSubgraphSchema(schema)
  .replace("_entities(representations: [_Any!]!): [_Entity]!", "")
  .replace("_service: _Service!", "");

const schemaOutput = `
### This file was generated by buildSchema.mjs
### Do not make changes to this file directly
${schemaText}`;

writeFileSync(destinationPath, schemaOutput, { encoding: "utf8" });
